%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__(<p>__start__</p>)
	Planning__(Planning模块)
	________(参考代码查询模块)
	______(代码生成模块)
	______(代码测试模块)
	______(代码验收模块)
	________(代码生成审查模块)
	______(记忆加载模块)
	______(记忆保存模块)
	______(记忆检索模块)
	______(决定是否完成)
	_____(结束前模块)
	__end__(<p>__end__</p>)
	Planning__ --> ________;
	__start__ --> Planning__;
	______ --> ______;
	________ --> ______;
	_____ --> __end__;
	______ -. &nbsp;end&nbsp; .-> _____;
	______ -. &nbsp;reflect&nbsp; .-> ________;
	______ -. &nbsp;generate&nbsp; .-> ______;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
